[2021-08-22 14:49:19,636] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures 2021-08-21T00:00:00+00:00 [queued]>
[2021-08-22 14:49:19,976] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures 2021-08-21T00:00:00+00:00 [queued]>
[2021-08-22 14:49:19,976] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-22 14:49:19,976] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-22 14:49:19,976] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-22 14:49:20,313] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): get_pictures> on 2021-08-21T00:00:00+00:00
[2021-08-22 14:49:20,319] {standard_task_runner.py:52} INFO - Started process 206 to run task
[2021-08-22 14:49:20,374] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'get_pictures', '2021-08-21T00:00:00+00:00', '--job-id', '60', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/download_rocket_launches.py', '--cfg-path', '/tmp/tmpze2vyzvv', '--error-file', '/tmp/tmp9zw5ajtn']
[2021-08-22 14:49:20,374] {standard_task_runner.py:77} INFO - Job 60: Subtask get_pictures
[2021-08-22 14:49:20,633] {logging_mixin.py:104} INFO - Running <TaskInstance: download_rocket_launches.get_pictures 2021-08-21T00:00:00+00:00 [running]> on host b4dfeeeb641c
[2021-08-22 14:49:21,143] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=get_pictures
AIRFLOW_CTX_EXECUTION_DATE=2021-08-21T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-21T00:00:00+00:00
[2021-08-22 14:49:21,147] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/download_rocket_launches.py", line 35, in _get_pictures
    image_urls = [launch["image"] for launch in launches["results"]]
KeyError: 'results'
[2021-08-22 14:49:21,152] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=get_pictures, execution_date=20210821T000000, start_date=20210822T144919, end_date=20210822T144921
[2021-08-22 14:49:21,339] {local_task_job.py:149} INFO - Task exited with return code 1
