[2021-08-22 15:31:12,577] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.download_launches 2021-08-22T15:31:10.299565+00:00 [queued]>
[2021-08-22 15:31:12,611] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.download_launches 2021-08-22T15:31:10.299565+00:00 [queued]>
[2021-08-22 15:31:12,612] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-22 15:31:12,612] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-22 15:31:12,612] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-22 15:31:12,628] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): download_launches> on 2021-08-22T15:31:10.299565+00:00
[2021-08-22 15:31:12,634] {standard_task_runner.py:52} INFO - Started process 2773 to run task
[2021-08-22 15:31:12,640] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'download_launches', '2021-08-22T15:31:10.299565+00:00', '--job-id', '91', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/1.rocket_launch_data.py', '--cfg-path', '/tmp/tmp6skm0pm_', '--error-file', '/tmp/tmphv4ngqrn']
[2021-08-22 15:31:12,641] {standard_task_runner.py:77} INFO - Job 91: Subtask download_launches
[2021-08-22 15:31:12,722] {logging_mixin.py:104} INFO - Running <TaskInstance: download_rocket_launches.download_launches 2021-08-22T15:31:10.299565+00:00 [running]> on host b4dfeeeb641c
[2021-08-22 15:31:12,817] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=download_launches
AIRFLOW_CTX_EXECUTION_DATE=2021-08-22T15:31:10.299565+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-22T15:31:10.299565+00:00
[2021-08-22 15:31:12,819] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-22 15:31:12,820] {subprocess.py:63} INFO - Running command: ['bash', '-c', "curl -o ./tmp/launches.json -L 'https://ll.thespacedevs.com/2.0.0/launch/upcoming'"]
[2021-08-22 15:31:12,833] {subprocess.py:74} INFO - Output:
[2021-08-22 15:31:12,850] {subprocess.py:78} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2021-08-22 15:31:12,850] {subprocess.py:78} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2021-08-22 15:31:13,237] {subprocess.py:78} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[2021-08-22 15:31:13,542] {subprocess.py:78} INFO - Warning: Failed to create the file ./tmp/launches.json: No such file or
[2021-08-22 15:31:13,542] {subprocess.py:78} INFO - Warning: directory
[2021-08-22 15:31:13,543] {subprocess.py:78} INFO - 100    71  100    71    0     0    102      0 --:--:-- --:--:-- --:--:--   102
[2021-08-22 15:31:13,543] {subprocess.py:78} INFO - curl: (23) Failed writing body (0 != 71)
[2021-08-22 15:31:13,543] {subprocess.py:82} INFO - Command exited with return code 23
[2021-08-22 15:31:13,694] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-08-22 15:31:13,696] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=download_launches, execution_date=20210822T153110, start_date=20210822T153112, end_date=20210822T153113
[2021-08-22 15:31:13,829] {local_task_job.py:149} INFO - Task exited with return code 1
